[build]
  publish = "out"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling
[build.environment]
  NODE_VERSION = "18"

# Handle form submissions
[[redirects]]
  from = "/contact"
  to = "/contact"
  status = 200

[[redirects]]
  from = "/registration"
  to = "/registration"
  status = 200
